// <auto-generated />
using System;
using AdessoTournamentApplication.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AdessoTournamentApplication.Data.Migrations
{
    [DbContext(typeof(AdtDbContext))]
    partial class AdtDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AdessoTournamentApplication.Data.Domain.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CountryId"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("AdessoTournamentApplication.Data.Domain.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GroupId"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("GroupId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("AdessoTournamentApplication.Data.Domain.GroupTeam", b =>
                {
                    b.Property<int>("GroupTeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GroupTeamId"));

                    b.Property<int?>("GroupId")
                        .HasColumnType("integer");

                    b.Property<int?>("TeamId")
                        .HasColumnType("integer");

                    b.HasKey("GroupTeamId");

                    b.HasIndex("GroupId");

                    b.HasIndex("TeamId");

                    b.ToTable("GroupTeams");
                });

            modelBuilder.Entity("AdessoTournamentApplication.Data.Domain.Team", b =>
                {
                    b.Property<int?>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("TeamId"));

                    b.Property<int?>("CountryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("TeamId");

                    b.HasIndex("CountryId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("AdessoTournamentApplication.Data.Domain.GroupTeam", b =>
                {
                    b.HasOne("AdessoTournamentApplication.Data.Domain.Group", "Group")
                        .WithMany("GroupTeams")
                        .HasForeignKey("GroupId");

                    b.HasOne("AdessoTournamentApplication.Data.Domain.Team", "Team")
                        .WithMany("GroupTeams")
                        .HasForeignKey("TeamId");

                    b.Navigation("Group");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("AdessoTournamentApplication.Data.Domain.Team", b =>
                {
                    b.HasOne("AdessoTournamentApplication.Data.Domain.Country", "Country")
                        .WithMany("Teams")
                        .HasForeignKey("CountryId");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("AdessoTournamentApplication.Data.Domain.Country", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("AdessoTournamentApplication.Data.Domain.Group", b =>
                {
                    b.Navigation("GroupTeams");
                });

            modelBuilder.Entity("AdessoTournamentApplication.Data.Domain.Team", b =>
                {
                    b.Navigation("GroupTeams");
                });
#pragma warning restore 612, 618
        }
    }
}
